kind: Deployment
apiVersion: apps/v1
metadata:
  name: homelab-api
  namespace: playground
  labels:
    app: homelab-api
    app.kubernetes.io/component: homelab-api
    app.kubernetes.io/instance: homelab-api
    app.kubernetes.io/name: homelab-api
    app.kubernetes.io/part-of: homelab-api-app
    app.openshift.io/runtime-namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homelab-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homelab-api
        deployment: homelab-api
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: homelab-api
          image: quay.io/jbatchel/homelab-api:v0.0.31
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: OTPSECRET
              valueFrom:
                secretKeyRef:
                  name: otp
                  key: OTPSECRET
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: homelab-api
  namespace: playground
  labels:
    app: homelab-api
    app.kubernetes.io/component: homelab-api
    app.kubernetes.io/instance: homelab-api
    app.kubernetes.io/name: homelab-api
    app.kubernetes.io/part-of: homelab-api-app
    app.openshift.io/runtime-namespace: playground
spec:
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: homelab-api
    deployment: homelab-api
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: homelab-api
  namespace: playground
  labels:
    app: homelab-api
    app.kubernetes.io/component: homelab-api
    app.kubernetes.io/instance: homelab-api
    app.kubernetes.io/name: homelab-api
    app.kubernetes.io/part-of: homelab-api-app
    app.openshift.io/runtime-namespace: playground
spec:
  host: homelab-api.apps.sno.purslane.io
  to:
    kind: Service
    name: homelab-api
    weight: 100
  port:
    targetPort: 5000-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None